cookie:
  expiry_days: 30
  key: lnp_formulation_auth_key_2025
  name: lnp_auth_cookie

credentials:
  usernames:
    admin:
      email: yue.xu@bcm.edu
      failed_login_attempts: 0
      first_name: Yue
      last_name: Xu
      logged_in: False
      password: admin123  # Will be hashed automatically
      roles:
        - admin
        - editor
    demo:
      email: demo@example.com
      failed_login_attempts: 0
      first_name: Demo
      last_name: User
      logged_in: False
      password: demo123  # Will be hashed automatically
      roles:
        - viewer
    lilab:
      email: lilab@bcm.edu
      failed_login_attempts: 0
      first_name: Li
      last_name: Lab
      logged_in: False
      password: lilab2025  # Will be hashed automatically
      roles:
        - admin
        - editor

pre-authorized:
  emails:
    - yue.xu@bcm.edu
    - lilab@bcm.edu

oauth2:
  google:
    client_id: YOUR_GOOGLE_CLIENT_ID
    client_secret: YOUR_GOOGLE_CLIENT_SECRET
  microsoft:
    client_id: YOUR_MICROSOFT_CLIENT_ID
    client_secret: YOUR_MICROSOFT_CLIENT_SECRET
    tenant_id: YOUR_MICROSOFT_TENANT_ID
